---

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka_z106
    restart: unless-stopped
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka/logs:/tmp/kraft-combined-logs
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "test-topic"

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      
      KAFKA_LISTENERS: PLAINTEXT://kafka_z106:9092,CONTROLLER://kafka_z106:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_z106:9093
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_NUM_PARTITIONS: 3

      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_RETENTION_BYTES: 4073741824
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      # KAFKA_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'







  postgres:
    container_name: postgres_z106
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 35432:5432
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  redis:
    image: redis
    container_name: redis_z106
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    ports:
      - "36379:6379"
    volumes: 
      - ./data/redis/data:/data

  minioserver:
      image: minio/minio
      ports:
        - 9000:9000
        - 9001:9001
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      container_name: minioserver
      command: server /data --console-address ":9001"
